
development:
  adapter: postgresql
  encoding: unicode
  database: relove_me_development
  pool: 5
  host: localhost
  username: annehomann
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: relove_me_development
  pool: 5
  password: